worker_processes auto;

events {
    worker_connections 1024;
}

stream {
    upstream chatserver_cluster {
        server chatserver-1:6000;
        server chatserver-2:6002;
    }

    server {
        listen 8000;
        proxy_connect_timeout 5s;
        proxy_timeout 1h;
        proxy_pass chatserver_cluster;
    }
}
